project_id = "uzymtgcklmunettdiucs"

[functions.auth-login-username]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.syrve-connect-test]
verify_jwt = false

[functions.syrve-save-config]
verify_jwt = false

[functions.syrve-sync]
verify_jwt = false

[functions.ai-recognize-label]
verify_jwt = false

[functions.generate-wine-embeddings]
verify_jwt = false
